# Generated by Django 2.2.1 on 2019-05-03 09:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_id', models.TextField()),
                ('password_id', models.TextField()),
                ('timezone_id', models.TextField()),
                ('time_id', models.TextField()),
                ('entry_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
